services:
  postgres_n8n:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_pass
      POSTGRES_DB: n8n_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_n8n:
    image: redis:7
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

#  ollama:
#    image: ollama/ollama:latest
#    restart: unless-stopped
#    ports:
#      - "11434:11434"   # API HTTP do Ollama
#    volumes:
#      - ollama_data:/root/.ollama
#    environment:
#      - OLLAMA_KEEP_ALIVE=24h   # mantém o modelo carregado em memória
#      - OLLAMA_MAX_LOADED_MODELS=2

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"     # API HTTP
      - "6334:6334"     # API gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # --- Banco Postgres ---
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres_n8n
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_pass
      
      # --- configura o n8n ----
      N8N_RUNNERS_ENABLED: true
      N8N_BLOCK_ENV_ACCESS_IN_NODE: false
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_ALLOW_EXTERNAL_MODULES: firebase-admin
      N8N_SECURITY_ALLOW_EXTERNAL_MODULES: firebase-admin
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom

      # --- Redis ---
      QUEUE_BULL_REDIS_HOST: redis_n8n
      QUEUE_BULL_REDIS_PORT: 6379

      # --- Segurança / Config ---
      # N8N_BASIC_AUTH_USER: admin
      # N8N_BASIC_AUTH_PASSWORD: senha-super-segura
      GENERIC_TIMEZONE: America/Sao_Paulo

      # --- Conexão com Qdrant ---
      QDRANT_URL: http://qdrant:6333

    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows
      # pasta local (no host) com os nodes customizados
      # cria ./custom-nodes na raiz do projeto
      - ./custom-nodes:/home/node/.n8n/custom
    depends_on:
      - postgres_n8n
      - redis_n8n
#      - ollama   # <--- garante que o n8n suba depois do Ollama
      - qdrant

volumes:
  postgres_data:
  redis_data:
  n8n_data:
#  ollama_data:
  qdrant_data:
